name: CI
on:
  push: { branches: [master]}
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.4.11f1
    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3

        # - name: Cache
        #   uses: actions/cache@v2.1.1

        - name: Unity - Test runner
          uses: webbertakken/unity-test-runner@v1.7

        - name: Unity - Builder
          uses: webbertakken/unity-builder@v1.4

        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: CISamplex86_64Binary
            path: /.bin-x86_64
    
        - name: Return license
          uses: webbertakken/unity-return-license@v1
          if: always()
    
        # - name: Decrypt Unity License 
        #   run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf
        
        # - name: Activate Unity License
        #   run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0
        
        # - name: Build x86_64 Binary 
        #   run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildLinux64Player ./bin-x86_64/CISample

        # - name: Archive Linux Build
        #   uses: actions/upload-artifact@v1
        #   with:
        #     name: CISamplex86_64Binary 
        #     path: ./bin-x86_64

        # - name: Delete Decrypted License 
        #   run: rm .github/Unity_v2019.x.ulf
