name: Github Actions Example

on:
                push:
                        branches:
                                - master

jobs:
        test:
                name: Running Unit Tests
                runs-on: ubuntu-latest
                

                steps:
                        - uses: actions/checkout@v2
                        - name: Use Node.js ${{ matrix.node-version }}
                          uses: actions/setup-node@v2
                          with: 
                                  node-version: ${{ matrix.node-version }}
                        - name: Install NPM
                          run: npm install
                        - name: Test
                          run: npm test
