name: Github Actions Example

on:
  push:
    branches:
       - master

jobs:
  test:
    name: Checkout   
    runs-on: ubuntu-latest
                

    steps:
    - uses: actions/checkout@v2
    

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: webbertakken/unity-builder@v1.2 
